# Generated by Django 4.2.4 on 2023-09-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='next_question',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_option', to='api.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='linked_question', to='api.option'),
        ),
    ]
