# Generated by Django 4.2.4 on 2023-09-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_option_next_question_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_next_question',
            field=models.BooleanField(default=False),
        ),
    ]
